# Numpy Usage for ML

### Import Numpy

In [1]:
import numpy as np

### Creating Arrays

In [2]:
one_d_array = np.array([2 , 4 , 6]) ### One Dimensional Array
print(one_d_array)

[2 4 6]


In [3]:
two_d_array = np.array([(2 , 4 , 6) , (1 , 3 , 5)])
print(two_d_array)

[[2 4 6]
 [1 3 5]]


### Data type, Item Size, Dimension

In [5]:
print(one_d_array.dtype)

int32


In [6]:
print(one_d_array.itemsize)

4


In [9]:
print(one_d_array.ndim)

1


### Array Size, Array Shape and Reshaping

In [12]:
print(two_d_array.size)

6


In [13]:
print(two_d_array.shape)

(2, 3)


In [16]:
two_d_array = two_d_array.reshape(3,2)
print(two_d_array)

[[2 4]
 [6 1]
 [3 5]]


### Linspace, Slice and Min-Max 

In [20]:
equally_spaced_array = np.linspace(10 , 20 , 4)
print(equally_spaced_array)

[10.         13.33333333 16.66666667 20.        ]


In [26]:
value_by_slice = two_d_array[0,1]
print(value_by_slice)

4


In [29]:
ranged_value_by_slice = two_d_array[0:3 , 1]
print(ranged_value_by_slice)

[4 1 5]


In [31]:
print(two_d_array.min())

1


In [32]:
print(two_d_array.max())

6


### Matrix Operations

In [33]:
array_1 = np.array([(2 , 4 , 6),(1 , 3 , 5)])
array_2 = np.array([(1 , 3 , 5),(2 , 4 , 6)])

In [34]:
print(array_1+array_2) #Matrix Addition

[[ 3  7 11]
 [ 3  7 11]]


In [35]:
print(array_1-array_2) #Matrix Subtraction

[[ 1  1  1]
 [-1 -1 -1]]


In [37]:
print(array_1*array_2) #Element Wise Multiplication

[[ 2 12 30]
 [ 2 12 30]]


In [38]:
print(array_1/array_2) #Element Wise Division

[[2.         1.33333333 1.2       ]
 [0.5        0.75       0.83333333]]


### Ravel, Sum of Axes

In [39]:
print(array_1.ravel()) #For printing an array in one line

[2 4 6 1 3 5]


In [41]:
print(array_1.sum(axis=0)) #Column sum, axis=0

[ 3  7 11]


In [42]:
print(array_1.sum(axis=1)) #Row sum, axis=1

[12  9]


### Square Root and Standard Deviation

In [44]:
print(np.sqrt(array_1)) #For square rooting each element

[[1.41421356 2.         2.44948974]
 [1.         1.73205081 2.23606798]]


In [45]:
print(np.std(array_1)) #Standard Deviation of Array

1.707825127659933


### Exponential and Logarithmic Functions

In [47]:
print(np.exp(array_1)) #e^x on each element of array

[[  7.3890561   54.59815003 403.42879349]
 [  2.71828183  20.08553692 148.4131591 ]]


In [48]:
print(np.log(array_1)) #log(x) on each element of array

[[0.69314718 1.38629436 1.79175947]
 [0.         1.09861229 1.60943791]]
